### ISSUE TITLE
No Scenarios

### ISSUE THREAD

**Issue by aalborz** [ermetic-research/cnappgoat#17]
After installing cnappgoat, when I run "cnappgoat list", it displays the following:

"ERRO[2023-09-14T12:11:04-04:00] no scenarios found"

Any ideas how I can resolve this?

**Comment by igofman** [comment]
Hi, thank you for bringing the issue to our attention. We released a new version v0.2.0, which incorporates a host of new features, bug fixes, and scenario updates. You can access this new version on our release page or upgrade through Homebrew.

We would appreciate your feedback to confirm whether the recent changes resolve the issues you've experienced.

**Comment by igofman** [comment]
No response
